In [1]:
import pandas as pd

In [2]:
pokemon_df = pd.read_csv('pokemonscraper\pokemon.csv', sep=',')

1010 unique values for Pokedex number is expected

In [3]:
pokemon_df['Pokedex Number'].nunique()

1010

The entries for the following pokemon need to be corrected:
 - Pikachu
 - Darmanitan
 - Pumpkaboo
 - Gourgeist

In [4]:
pokemon_df[pokemon_df['Pokedex Number']==25]

,Pokedex Number,Pokemon,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Group
1139,25,Pikachu,Electric,NaN,300,35,55,30,50,40,90,1,Standard
1140,25,Cosplay Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,Standard
1141,25,Pikachu in a cap,Electric,NaN,300,35,55,30,50,40,90,1,Standard
1142,25,Partner Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,Standard

In [5]:
pokemon_df[pokemon_df['Pokedex Number']==25].drop([pokemon_df.index[1141], pokemon_df.index[1142], pokemon_df.index[1139]]).replace(['Cosplay Pikachu'], 'Pikachu')

,Pokedex Number,Pokemon,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Group
1140,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,Standard

In [6]:
pokemon_df = pokemon_df.drop([pokemon_df.index[1141], pokemon_df.index[1142], pokemon_df.index[1139]])
pik = pokemon_df.loc[pokemon_df['Pokemon'] == 'Cosplay Pikachu'].index[0]
pokemon_df.loc[[pik], ['Pokemon']]=['Pikachu']

In [7]:
pokemon_df[pokemon_df['Pokedex Number']==25]

,Pokedex Number,Pokemon,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Group
1140,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,Standard

Pikachu entry corrected and removed extra entries

In [8]:
pokemon_df[pokemon_df['Pokedex Number']==555]

,Pokedex Number,Pokemon,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Group
502,555,Darmanitan Standard Mode,Fire,NaN,480,105,140,55,30,55,95,5,Standard
503,555,Darmanitan Galarian Standard Mode,Ice,NaN,540,105,30,105,140,105,55,5,Regional Form
504,555,Darmanitan Zen Mode,Fire,Psychic,540,105,160,55,30,55,135,5,Standard
505,555,Darmanitan Galarian Zen Mode,Ice,Fire,480,105,140,55,30,55,95,5,Regional Form

In [9]:
dar1 = pokemon_df.loc[pokemon_df['Pokemon'] == 'Darmanitan Galarian Standard Mode'].index[0]
dar2 = pokemon_df.loc[pokemon_df['Pokemon'] == 'Darmanitan Galarian Zen Mode'].index[0]
dar3 = pokemon_df.loc[pokemon_df['Pokemon'] == 'Darmanitan Zen Mode'].index[0]
pokemon_df.loc[[dar1], ['Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']]=[480, 105, 140, 55, 30, 55, 95]
pokemon_df.loc[[dar2], ['Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']]=[540, 105, 160, 55, 30, 55, 135]
pokemon_df.loc[[dar3], ['Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']]=[540, 105, 30, 105, 140, 105, 55]

In [10]:
pokemon_df[pokemon_df['Pokedex Number']==555]

,Pokedex Number,Pokemon,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Group
502,555,Darmanitan Standard Mode,Fire,NaN,480,105,140,55,30,55,95,5,Standard
503,555,Darmanitan Galarian Standard Mode,Ice,NaN,480,105,140,55,30,55,95,5,Regional Form
504,555,Darmanitan Zen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,Standard
505,555,Darmanitan Galarian Zen Mode,Ice,Fire,540,105,160,55,30,55,135,5,Regional Form

Darmanitan entries have been corrected and now the missing sizes for Gourgeist and Pumpkaboo will be added and corrected

In [11]:
gourgeist = pokemon_df.loc[pokemon_df['Pokemon'] == 'Gourgeist Super Size'].index[0]
pokemon_df.loc[[gourgeist], ['Pokemon']]=['Gourgeist Average Size']
missing_sizes = {
    'Pokedex Number': [711, 711, 711],
    'Pokemon': ['Gourgeist Small Size', 'Gourgeist Large Size', 'Gourgeist Super Size'],
    'Type 1': ['Ghost', 'Ghost', 'Ghost'],
    'Type 2': ['Grass', 'Grass', 'Grass'],
    'Total': [494, 494, 494],
    'HP': [55, 75, 85],
    'Attack': [85, 95, 100],
    'Defense': [122, 122, 122],
    'Sp. Atk': [58, 58, 58],
    'Sp. Def': [75, 75, 75],
    'Speed': [99, 69, 54],
    'Generation': [6, 6, 6],
    'Group': ['Standard', 'Standard', 'Standard']
}
missing_df = pd.DataFrame(missing_sizes)
pokemon_df = pd.concat([pokemon_df, missing_df], axis=0)

In [12]:
pokemon_df[pokemon_df['Pokedex Number']==711]

,Pokedex Number,Pokemon,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Group
332,711,Gourgeist Average Size,Ghost,Grass,494,65,90,122,58,75,84,6,Standard
0,711,Gourgeist Small Size,Ghost,Grass,494,55,85,122,58,75,99,6,Standard
1,711,Gourgeist Large Size,Ghost,Grass,494,75,95,122,58,75,69,6,Standard
2,711,Gourgeist Super Size,Ghost,Grass,494,85,100,122,58,75,54,6,Standard

Gourgeist now corrected

In [13]:
pumpkaboo = pokemon_df.loc[pokemon_df['Pokemon'] == 'Pumpkaboo Super Size'].index[0]
pokemon_df.loc[[gourgeist], ['Pokemon']]=['Pumpkaboo Average Size']
missing_sizes = {
    'Pokedex Number': [710, 710, 710],
    'Pokemon': ['Pumpkaboo Small Size', 'Pumpkaboo Large Size', 'Pumpkaboo Super Size'],
    'Type 1': ['Ghost', 'Ghost', 'Ghost'],
    'Type 2': ['Grass', 'Grass', 'Grass'],
    'Total': [335, 335, 335],
    'HP': [44, 54, 59],
    'Attack': [66, 66, 66],
    'Defense': [70, 70, 70],
    'Sp. Atk': [44, 44, 44],
    'Sp. Def': [55, 55, 55],
    'Speed': [56, 46, 41],
    'Generation': [6, 6, 6],
    'Group': ['Standard', 'Standard', 'Standard']
}
missing_df = pd.DataFrame(missing_sizes)
pokemon_df = pd.concat([pokemon_df, missing_df], axis=0)

In [14]:
pokemon_df[pokemon_df['Pokedex Number']==710]

,Pokedex Number,Pokemon,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Group
333,710,Pumpkaboo Super Size,Ghost,Grass,335,49,66,70,44,55,51,6,Standard
0,710,Pumpkaboo Small Size,Ghost,Grass,335,44,66,70,44,55,56,6,Standard
1,710,Pumpkaboo Large Size,Ghost,Grass,335,54,66,70,44,55,46,6,Standard
2,710,Pumpkaboo Super Size,Ghost,Grass,335,59,66,70,44,55,41,6,Standard

Pumpkaboo now corrected

In [15]:
pokemon_df = pokemon_df.sort_values(by=['Pokedex Number', 'Total'], ascending=True)

In [16]:
pokemon_df['Group'].dtype

dtype('O')

In [17]:
pokemon_df['Group'] = pokemon_df['Group'].apply(lambda x: list(x.split(',')))

In [18]:
filter = pokemon_df['Group'].apply(lambda x: 'Regional Form' in x)
pokemon_df[filter]

,Pokedex Number,Pokemon,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Group
1150,19,Alolan Rattata,Dark,Normal,253,30,56,35,25,35,72,1,[Regional Form]
1148,20,Alolan Raticate,Dark,Normal,413,75,71,70,40,80,77,1,[Regional Form]
1138,26,Alolan Raichu,Electric,Psychic,485,60,85,50,95,85,110,1,[Regional Form]
1136,27,Alolan Sandshrew,Ice,Steel,300,50,75,90,10,35,40,1,[Regional Form]
1134,28,Alolan Sandslash,Ice,Steel,450,75,100,120,25,65,65,1,[Regional Form]
1124,37,Alolan Vulpix,Ice,NaN,299,38,41,40,50,65,65,1,[Regional Form]
1122,38,Alolan Ninetales,Ice,Fairy,505,73,67,75,81,100,109,1,[Regional Form]
1109,50,Alolan Diglett,Ground,Steel,265,10,55,30,35,45,90,1,[Regional Form]
1107,51,Alolan Dugtrio,Ground,Steel,425,35,100,60,50,70,110,1,[Regional Form]
1104,52,Galarian Meowth,Steel,NaN,290,40,35,35,50,40,90,1,[Regional Form]
1105,52,Alolan Meowth,Dark,NaN,290,50,65,55,40,40,40,1,[Regional Form]
1102,53,Alolan Persian,Dark,NaN,440,65,60,60,75,65,115,1,[Regional Form]
1096,58,Hisuian Growlithe,Fire,Rock,350,60,75,45,65,50,55,1,[Regional Form]
1094,59,Hisuian Arcanine,Fire,Rock,555,95,115,80,95,80,90,1,[Regional Form]
1077,74,Alolan Geodude,Rock,Electric,300,40,80,100,30,30,20,1,[Regional Form]
1075,75,Alolan Graveler,Rock,Electric,390,55,95,115,45,45,35,1,[Regional Form]
1073,76,Alolan Golem,Rock,Electric,495,80,120,130,55,65,45,1,[Regional Form]
1071,77,Galarian Ponyta,Psychic,NaN,410,50,85,55,65,65,90,1,[Regional Form]
1069,78,Galarian Rapidash,Psychic,Fairy,500,65,100,70,80,80,105,1,[Regional Form]
1067,79,Galarian Slowpoke,Psychic,NaN,315,90,65,65,40,40,15,1,[Regional Form]
1064,80,Galarian Slowbro,Poison,Psychic,590,95,75,180,130,80,30,1,[Regional Form]
1060,83,Galarian Farfetch'd,Fighting,NaN,377,52,95,55,58,62,55,1,[Regional Form]
1054,88,Alolan Grimer,Poison,Dark,325,80,80,50,40,50,25,1,[Regional Form]
1052,89,Alolan Muk,Poison,Dark,500,105,105,75,65,100,50,1,[Regional Form]
1039,100,Hisuian Voltorb,Electric,Grass,330,40,30,50,55,55,100,1,[Regional Form]
1037,101,Hisuian Electrode,Electric,Grass,490,60,50,70,80,80,150,1,[Regional Form]
1034,103,Alolan Exeggutor,Grass,Dragon,530,95,105,85,125,75,45,1,[Regional Form]
1031,105,Alolan Marowak,Fire,Ghost,425,60,80,110,50,80,45,1,[Regional Form]
1025,110,Galarian Weezing,Poison,Fairy,490,65,90,120,85,70,60,1,[Regional Form]
1011,122,Galarian Mr. Mime,Ice,Psychic,460,50,65,65,90,90,100,1,[Regional Form]
1001,128,Paldean Tauros Combat Breed,Fighting,NaN,490,75,110,105,30,70,100,1,[Regional Form]
1002,128,Paldean Tauros Blaze Breed,Fighting,Fire,490,75,110,105,30,70,100,1,[Regional Form]
1003,128,Paldean Tauros Aqua Breed,Fighting,Water,490,75,110,105,30,70,100,1,[Regional Form]
982,144,Galarian Articuno,Psychic,Flying,580,90,85,85,125,100,95,1,"[Legendary, Regional Form]"
980,145,Galarian Zapdos,Fighting,Flying,580,90,125,90,85,90,100,1,"[Legendary, Regional Form]"
978,146,Galarian Moltres,Dark,Flying,580,90,85,90,100,125,90,1,"[Legendary, Regional Form]"
964,157,Hisuian Typhlosion,Fire,Ghost,534,73,84,78,119,85,95,2,[Regional Form]
925,194,Paldean Wooper,Poison,Ground,210,55,45,45,25,25,15,2,[Regional Form]
919,199,Galarian Slowking,Poison,Psychic,490,95,65,80,110,110,30,2,[Regional Form]
905,211,Hisuian Qwilfish,Dark,Poison,440,65,95,85,55,55,85,2,[Regional Form]
898,215,Hisuian Sneasel,Fighting,Poison,430,55,95,55,35,75,115,2,[Regional Form]
890,222,Galarian Corsola,Ghost,NaN,410,60,55,100,65,100,30,2,[Regional Form]
843,263,Galarian Zigzagoon,Dark,Normal,240,38,30,41,30,41,60,3,[Regional Form]
841,264,Galarian Linoone,Dark,Normal,420,78,70,61,50,61,100,3,[Regional Form]
561,503,Hisuian Samurott,Water,Dark,528,90,108,80,100,65,85,5,[Regional Form]
513,549,Hisuian Lilligant,Grass,Fighting,480,70,105,75,50,75,105,5,[Regional Form]
507,554,Galarian Darumaka,Ice,NaN,315,70,90,45,15,45,50,5,[Regional Form]
503,555,Darmanitan Galarian Standard Mode,Ice,NaN,480,105,140,55,30,55,95,5,[Regional Form]
505,555,Darmanitan Galarian Zen Mode,Ice,Fire,540,105,160,55,30,55,135,5,[Regional Form]
495,562,Galarian Yamask,Ground,Ghost,303,38,55,85,30,65,30,5,[Regional Form]
486,570,Hisuian Zorua,Normal,Ghost,330,35,60,40,85,40,70,5,[Regional Form]
484,571,Hisuian Zoroark,Normal,Ghost,510,55,100,60,125,60,110,5,[Regional Form]
437,618,Galarian Stunfisk,Ground,Steel,471,109,81,99,66,84,32,5,[Regional Form]
426,628,Hisuian Braviary,Psychic,Flying,510,110,83,70,112,70,65,5,[Regional Form]
340,705,Hisuian Sliggoo,Steel,Dragon,452,58,75,83,83,113,40,6,[Regional Form]
338,706,Hisuian Goodra,Steel,Dragon,600,80,100,100,110,150,60,6,"[Pseudo-legendary, Regional Form]"
330,713,Hisuian Avalugg,Ice,Rock,514,95,127,184,34,36,38,6,[Regional Form]
314,724,Hisuian Decidueye,Grass,Fighting,530,88,112,80,95,95,60,7,[Regional Form]

In [19]:
pokemon_df.to_csv('pokemon_cleaned.csv', index=False)